services:
  db:
    image: postgres:latest
    container_name: mentorlik_postgres
    environment:
      POSTGRES_DB: mentorlik_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mentorlik-network

  db_backup:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile.backup
    environment:
      POSTGRES_DB: mentorlik_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backup:/backups
    networks:
      - mentorlik-network
    depends_on:
      - db

networks:
  mentorlik-network:
    driver: bridge