version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mentorlik_postgres
    environment:
      POSTGRES_DB: mentorlik_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - mentorlik-network

  db_backup:
    build:
      context: ./postgres
      dockerfile: Dockerfile.backup
    environment:
      POSTGRES_DB: mentorlik_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres/backup:/backups
    networks:
      - mentorlik-network
    depends_on:
      - db

  backend:
    build:
      context: ../backend
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - mentorlik-network
    depends_on:
      - db

networks:
  mentorlik-network:
    driver: bridge