version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:14-alpine
    container_name: mentorlik_postgres
    environment:
      POSTGRES_DB: mentorlik_db
      POSTGRES_USER: ${DB_USERNAME:-mentorlik_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mentorlik_password}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - mentorlik-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-mentorlik_user} -d mentorlik_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin - PostgreSQL Admin
  pgadmin:
    image: dpage/pgadmin4
    container_name: mentorlik_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mentorlik.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - mentorlik-network
    depends_on:
      - db
    restart: unless-stopped

networks:
  mentorlik-network:
    driver: bridge 