spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mentorlik_test_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          linkedin:
            redirect-uri: "{baseUrl}/login/oauth2/code/linkedin"

logging:
  level:
    root: WARN
    org.springframework: INFO