spring:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          linkedin:
            redirect-uri: "{baseUrl}/login/oauth2/code/linkedin"

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG