spring:
  datasource:
    url: jdbc:h2:mem:mentorlik_test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
    org.springframework: INFO
server:
  port: 8082
