spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/mentorlik_prod_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          linkedin:
            redirect-uri: "{baseUrl}/login/oauth2/code/linkedin"

logging:
  level:
    root: INFO
    org.springframework: WARN